### ISSUE TITLE
Design /font

### ISSUE THREAD

**Issue by deadlight** [ubuntudesign/design.ubuntu.com-design#4]
Goals:

Make the settings more concise
Settings below the text, not above
Text bigger and bolder to start with

_From @deadlight on June 5, 2017 14:1_

Design font page after UX review

_Copied from original issue: canonical-websites/design.ubuntu.com#28_

**Comment by frankiegranato** [comment]
This is the WIP design (not finalised). re the Tool component - This is the preferred option by UX and DEVs (filters sit before the preview box). 
![003](https://user-images.githubusercontent.com/17002826/27079927-a327f138-5031-11e7-9288-aac453c522b1.png)

**Comment by joanasa89** [comment]
The most recent design for design.ubuntu.com/font including the copy from copy doc.

![Uploading 001 I Fonts page - final designs.jpg…]()

**Comment by spencerbygraves** [comment]
@joanasa89 Could we take another look at the styling for Facts and figures and Resources please.

If you look at the current site, Facts and figures uses bullet points which makes the content easier to read. And perhaps we can display the Resources links a bit better, is there a pattern with dividing lines for example?

**Comment by joanasa89** [comment]
Updated:
![Uploading 001 I Fonts page - final designs.jpg…]()

**Comment by spencerbygraves** [comment]
Thanks @joanasa89. One small detail, the paragraph of text under the Design heading doesn't seem to be the correct width.

**Comment by joanasa89** [comment]
You right. I've amended to 7col. 
Also I've changed the "About ubuntu family" paragraph to 8 col (is the maximum of col we use)

![001 i fonts page - final designs](https://user-images.githubusercontent.com/21334617/27223688-7b3312de-5289-11e7-92b2-9e0ce975080b.jpg)
