### ISSUE TITLE
Update content of /brand/screenshots

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/design.ubuntu.com-design#8]
The content on this page http://design.ubuntu.com/brand/screenshots is out of date. It should include:
- What elements should be present in desktop screenshots (e.g. wifi icon, battery level, time, apps, etc.)
- Cropping guidelines
- Examples

Make sure that this is done in a Google Doc in the project folder, following the same format as the other pages.

**Comment by anasereijo** [comment]
closing as we are redesigning the website
