### ISSUE TITLE
Update content in /brand/photography

### ISSUE THREAD

**Issue by yaili** [ubuntudesign/design.ubuntu.com-design#9]
The current page http://design.ubuntu.com/brand/photography includes some things which are out of date and is missing information. Things to cover:
- Include examples from latest photoshoots
- Remove references to audience sliders, dots, tints
- Include guidelines for new photoshoots

Make sure that this is done in a Google Doc in the project folder, following the same format as the other pages.

**Comment by anasereijo** [comment]
closing as we are redesigning the website.
